;; slime
(use-package slime)
(use-package slime-company)
(setq inferior-lisp-program "/usr/bin/sbcl")
(when (eq system-type 'darwin)
  (setq inferior-lisp-program "/usr/local/bin/sbcl"))
(setq slime-contribs '(slime-fancy))
(slime-setup '(slime-fancy slime-company))
(define-key company-active-map (kbd "\C-n") 'company-select-next)
(define-key company-active-map (kbd "\C-p") 'company-select-previous)
(define-key company-active-map (kbd "\C-d") 'company-show-doc-buffer)
(define-key company-active-map (kbd "M-.") 'company-show-location)
